{{- with .Values.wellKnownDelegation }}
{{- if .httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-well-known
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.well-known-delegation-ingress.labels" (dict "root" $ "context" $.Values.haproxy) | nindent 4 }}
spec:
  parentRefs:
    {{- required "A valid .Values.httpRoute.parentRefs entry is required when httpRoute.enabled is true" $.Values.httpRoute.parentRefs | toYaml | nindent 4 }}
  {{- with .httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
{{- if and .baseDomainRedirect.enabled (or $.Values.elementWeb.enabled .baseDomainRedirect.url) }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $.Release.Name }}-well-known
          port: 8010
{{- else }}
    - matches:
        - path:
            type: PathPrefix # TODO: path type
            value: /.well-known/matrix
      backendRefs:
        - name: {{ $.Release.Name }}-well-known
          port: 8010
{{- end }}
{{- end }}
{{- end }}
