{{- with .Values.hookshot }}
{{- if .httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-hookshot
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.hookshot.labels" (dict "root" $ "context" $.Values.haproxy) | nindent 4 }}
spec:
  parentRefs:
    {{- required "A valid .Values.httpRoute.parentRefs entry is required when httpRoute.enabled is true" $.Values.httpRoute.parentRefs | toYaml | nindent 4 }}
  {{- with .httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /widgeapi/v1
      backendRefs:
        - name: {{ $.Release.Name }}-hookshot
          port: 7778
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $.Release.Name }}-hookshot
          port: 7775
{{- end }}
{{- end }}
