{{- with .Values.matrixRTC }}
{{- if .httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-matrix-rtc
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "element-io.matrix-rtc-ingress.labels" (dict "root" $ "context" .) | nindent 4 }}
spec:
  parentRefs:
    {{- required "A valid .Values.httpRoute.parentRefs entry is required when httpRoute.enabled is true" $.Values.httpRoute.parentRefs | toYaml | nindent 4 }}
  {{- with .httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /sfu/get
      backendRefs:
        - name: {{ $.Release.Name }}-matrix-rtc-authorisation-service
          port: 8080
{{ if .sfu.enabled }}
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ $.Release.Name }}-matrix-rtc-sfu
          port: 7880
{{- end }}
{{- end }}
{{- end }}
